### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by Xaiku** [UofS-Pulse-Binfo/nd_genotypes#51]
Versions:
Tripal: 3
Drupal: 7.69
Postgres: 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1)
PHP: 7.3.24-3+ubuntu18.04.1+deb.sury.org+1

After loading in the vcf files with Genotypes Loader, I am trying to use ND genotypes to visualize the data, but when I try to Sync with Tripalus I get the following error:

![image](https://user-images.githubusercontent.com/73877812/100746743-68922b00-33e1-11eb-8ae0-c436973e54fc.png)

Can someone help me with this error? Thank you in advance.

**Comment by laceysanderson** [comment]
Hi @Xaiku,

`drush_log` is provided by the command-line tool Drush. It's generally assumed that all Tripal Jobs are run using Drush since they are long running and often will not complete within the page load. 

Did you attempt to run the sync job through the Tripal jobs interface or on the command line using `drush trp-job-run`? If you did use the interface, can you please use the command-line instead. 

I'll add a note to the documentation to make it clear that sync especially should always be run on the command-line.

**Comment by Xaiku** [comment]
Hey @laceysanderson, It worked! Thank you!

**Comment by laceysanderson** [comment]
Awesome! Glad to hear! Let me know if there is anything else you come across where I could improve documentation or usability of the module :-)
